repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: |
          jupyter nbconvert
          --inplace
          --ClearOutputPreprocessor.enabled=True
          --ClearMetadataPreprocessor.enabled=True
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.9.10
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       args: [--fix]
  #     # Run the formatter.
  #     - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml